### ISSUE TITLE
[BUG] ic-pstats output showing inflated values for sizes

### ISSUE THREAD

**Issue by dipanshah** [instaclustr/cassandra-sstable-tools#19] opened 2023-05-10 11:49 UTC
**Describe the bug**
Hello,
We are facing an issue with the ic-pstats on Cassandra V2 where the output of ic-pstats is showing table sizes at about 10x than what is displayed using "du -sh" on our servers.

**To Reproduce**
For example,

Sizes from linux shell:
[user@server]$ du -sh * | grep Data.db
5.3G	k-t-ka-3566231-Data.db
43G     k-t-ka-3566232-Data.db
8.7G	k-t-ka-3566235-Data.db
9.2G	k-t-ka-3566236-Data.db
281M	k-t-ka-3566237-Data.db
2.3G	k-t-ka-3566238-Data.db
79G     k-t-ka-3566239-Data.db
697M	k-t-ka-3566242-Data.db
194M	k-t-ka-3566247-Data.db
496M	k-t-ka-3566256-Data.db
159M	k-t-ka-3566261-Data.db
48M	k-t-ka-3566262-Data.db

Sizes from ic-pstats:
SSTables:
+----------------------------+----------+-------------------------+-------------------------+-------+------------+--------------------+--------------------+
| SSTable                    | Size     | Min Timestamp           | Max Timestamp           | Level | Partitions | Avg Partition Size | Max Partition Size |
+----------------------------+----------+-------------------------+-------------------------+-------+------------+--------------------+--------------------+
| k-t-ka-3566231-Data.db |  47.1 GB | 2018-06-28 13:43:37.017 | 2022-12-07 18:05:09.294 |     0 |    1169960 |            40.3 kB |            76.2 MB |
| k-t-ka-3566232-Data.db | 394.7 GB | 2018-05-02 14:44:33.379 | 2022-10-31 18:34:23.681 |     0 |    8845889 |            44.6 kB |           276.7 MB |
| k-t-ka-3566235-Data.db |  79.8 GB | 2018-05-02 15:45:37.477 | 2023-04-03 18:35:59.361 |     0 |    1843560 |            43.3 kB |            34.5 MB |
| k-t-ka-3566236-Data.db |  84.1 GB | 2018-05-02 14:44:47.370 | 2023-02-04 18:16:15.122 |     0 |    1983864 |            42.4 kB |            51.2 MB |
| k-t-ka-3566237-Data.db |   2.2 GB | 2018-11-29 05:14:52.502 | 2023-03-24 12:42:03.975 |     0 |      79023 |            27.8 kB |             6.2 MB |
| k-t-ka-3566238-Data.db |  20.2 GB | 2018-07-05 04:13:49.724 | 2023-04-19 00:55:43.314 |     0 |     505155 |            40.1 kB |            11.1 MB |
| k-t-ka-3566239-Data.db | 681.2 GB | 2018-05-02 14:44:18.494 | 2021-12-15 15:19:41.094 |     0 |   21152939 |            32.2 kB |             1.1 GB |
| k-t-ka-3566242-Data.db |   6.0 GB | 2018-05-02 14:44:41.400 | 2023-04-20 18:01:43.291 |     0 |     165167 |            36.2 kB |             8.1 MB |
| k-t-ka-3566247-Data.db |   1.6 GB | 2018-09-06 13:53:53.353 | 2023-04-22 18:43:14.779 |     0 |      52510 |            29.9 kB |             4.1 MB |
| k-t-ka-3566256-Data.db |   3.9 GB | 2018-06-26 17:39:24.745 | 2023-04-24 17:43:05.252 |     0 |     125750 |            31.2 kB |            16.0 MB |
| k-t-ka-3566261-Data.db |   1.2 GB | 2019-02-08 05:14:38.296 | 2023-04-25 13:05:16.766 |     0 |      46096 |            25.8 kB |             2.7 MB |
+----------------------------+----------+-------------------------+-------------------------+-------+------------+--------------------+--------------------

**Expected behavior**
We were expecting the size of the data file will be the same from the linux shell and the ic-pstats output.

**System and versions (please complete the following information):**
 - OS: Ubuntu
 - Cassandra version: V2.1
 - Java version: Java 8
 - SSTable tools version: 2.1

**Comment by smiklosovic** [comment] 2023-05-12 09:12
I do not think this tool supports Cassandra of version 2.x. Is this happening in Cassandra 3.x as well? 

cc @grom358

**Comment by grom358** [comment] 2023-05-12 10:22
@dipanshah the sizes listed in SSTable section of ic-pstats there are the uncompressed sizes. There documentation of the fields here https://www.instaclustr.com/support/documentation/cassandra/using-cassandra/ic-tools-for-cassandra-sstables/#section-ic-pstats

If you use ic-sstables it has columns for both disk size and uncompressed size.

**Comment by smiklosovic** [comment] 2023-05-28 17:21
closed as this is not a bug

**Closed as completed by smiklosovic** 2023-05-28 17:21 UTC
Labels: bug
